# Generated by Django 4.1.2 on 2022-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_alter_user_is_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
