repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.bumpversion.cfg'
      - id: debug-statements

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args: ['--py36-plus']

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.3
    hooks:
      - id: isort
        files: \.py$

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        types: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-blind-except',
          'flake8-bandit',
          'flake8-comprehensions',
          'flake8-mutable',
          'flake8-bugbear'
        ]
