FROM nginx:stable-alpine

WORKDIR /app

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx-conf.d /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/

COPY project/static static
COPY project/media media