# https://tproger.ru/translations/docker-instuction/
# --------------------------------------------------

# базовый образ
FROM python

# переменные окружения
ENV PYTHONUNBUFFERED=1 \
	PYTHONDONTWRITEBYTECODE=1 \
	FROM_DOCKER_IMAGE=True

RUN mkdir /code

# задаем рабочую директорию в контексте Dockerfile. далее можно пользоваться "." и писать относительные пути (относительно директории /code)
WORKDIR /code

# копируем файлы проекта в контейнер
COPY . .
COPY ["pyproject.toml", "poetry.lock", "./"]

# устанавливаем poetry и ставим зависимости в локальное окружение
RUN pip install poetry
RUN poetry install

# RUN python ./project/manage.py collectstatic

# точка входа в приложение. формат: ["<command>" "<arg1>", "<arg2>", ..., "<argn>"]
# не нужно писать code/project/manage.py, т.к. code/ является рабочей директорией (см. WORKDIR выше)
ENTRYPOINT ["poetry", "run", "python", "./project/manage.py", "runserver", "0.0.0.0:8000"]