version: "3.8"

services:

  db:
    container_name: django_postgres
    hostname: django_postgres
    image: postgres:alpine
    env_file: src/.env
    ports:
      - "5430:5432"
    volumes:
      - ./django_postgres:/var/lib/postgresql/dat
      # специальная директория для автовыполнения .sql скриптов
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  web:
    container_name: web
    env_file: src/.env
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
      - celery

  redis:
    container_name: redis
    image: redis:alpine
    ports:
     - "6379:6379"
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    env_file: src/.env
    command: ["/app/docker/run-celery.sh"]
    volumes:
      - .:/code
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
     - "80:80"
    depends_on:
      - web

  flower:
    container_name: flower
    image: mher/flower:latest
    volumes:
      - ./flower:/app
    ports:
      - "5557:5555"
    depends_on:
      - celery

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    env_file: src/.env
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq
        - ./rabbitmq/log/:/var/log/rabbitmq
