# Generated by Django 4.1.2 on 2022-11-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscriber',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
