# Generated by Django 4.1.2 on 2022-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_alter_user_is_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
