# Generated by Django 4.1.5 on 2023-03-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_news_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user',
            new_name='author',
        ),
    ]
