name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPOSITORY: nightblure
      IMAGE_TAG: latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: flake8
        run: flake8 .

#      - name: tests
#        run: |
#          cd project
#          pytest -rs

      - name: Build and push Docker image on Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
          docker build . --file ./Dockerfile --tag $DOCKER_REPOSITORY/django-news:$IMAGE_TAG --no-cache
          docker push $DOCKER_REPOSITORY/django-news:$IMAGE_TAG

#      - name: Install Poetry
#        uses: snok/install-poetry@v1
#        with:
#          virtualenvs-in-project: true
#
#      - name: Install dependencies
#        run: poetry install --no-interaction
